name: Copy Secrets to BLU_Classic

on:
  workflow_dispatch:

jobs:
  copy-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Copy secrets to BLU_Classic
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
        run: |
          # The secrets are available as environment variables in this workflow
          # We can use them to set secrets in BLU_Classic
          
          echo "Setting CF_API_KEY in BLU_Classic..."
          echo "$CF_API_KEY" | gh secret set CF_API_KEY --repo DonnieDice/BLU_Classic
          
          echo "Setting WAGO_API_TOKEN in BLU_Classic..."
          echo "$WAGO_API_TOKEN" | gh secret set WAGO_API_TOKEN --repo DonnieDice/BLU_Classic
          
          echo "Setting WOWI_API_TOKEN in BLU_Classic..."
          echo "$WOWI_API_TOKEN" | gh secret set WOWI_API_TOKEN --repo DonnieDice/BLU_Classic
          
          echo "Secrets copied successfully!"
          
          # Verify they were set
          gh secret list --repo DonnieDice/BLU_Classic